theme = "onedark"

[editor.cursor-shape]
insert = "bar"
select = "underline"
normal = "block"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[keys.normal."+"]
b = ":run-shell-command cargo build"
